GeyserMC/GeyserWiki

_docs/geyser/root.md, _docs/geyser/setup.md
Fixes the setup page stating 1.17.30 was the oldest currently supported bedrock version when in reality it's 1.17.40.
=> Update supported versions

_docs/floodgate/setup.md
not sure if theres a cleaner way to get docsy to link links? or even do it automatically
=> hyperlink downloads on floodgate setup page

_data/providers.json
Remove hokus from providers list as host is no longer operating. Confirmation of this can be seen by visiting their website (hokus.me), a modal will appear notifying the user of the host's closure.
=> Remove hokus from providers list

pages/index.md
By setting head element to 2 the tittle does not get added to TOC sidebar links.
=> fix #undefined dead TOC links on index page.

_data/providers.json
Based on the existing data for Google Cloud, but amended to point to the Oracle Cloud blog post regarding how to set up a Minecraft server on OCI.
Also included a resolution to UFW being broken on Oracle Cloud’s Ubuntu images.
=> Add Oracle Cloud to providers.json

_docs/geyser/anticheat-compatibility.md
Light Anti Cheat got removed from the list since it doesn't exist anymore.
=> Removed lac from anticheat-compatibility.md 

_docs/geyser/understanding-the-config.md
explains the unusable-space-block option in the geyser config, and give further example of how it works.
=> adding the unusable-space-block config option

_docs/geyser/understanding-the-config.md
It's `above-bedrock-nether-building`, not `above-nether-bedrock-building`.
=> Fix bedrock nether config typo

_docs/geyser/anticheat-compatibility.md
Since early January 2023, bedrock detections for the Spartan AntiCheat are available fully by the default file/purchase and without the need for an additional purchase like previously, so I've adjusted its description and list.
=> Spartan AntiCheat Adjustment

_data/providers.json, _docs/geyser/supported-hosting-providers.md
Hi there,
The company Netbela (hosting company from the Netherlands) supports the use of this plugin, Could you perhaps add the following to the 'Support for Geyser' list? Link: https://netbela.nl/store/minecraft
Name: Netbela
Description: Install Geyser as a plugin with the dedicated Plugin installer. 
Use the same port as your Java server for the Bedrock address and port in your config and connect with that specific address and port.
=> Adding of Netbela to the list of Hosting providers

_data/providers.json
[Minefort](https://minefort.com/) is a full-featured free Minecraft server hosting. We support Geyser out of the box on every server. Users simply need to make sure it is enabled in their server dashboard.
=> Add Minefort to the list of hosting providers

_docs/other/community-geyser-projects.md
Considering TC doesn't have a server anymore, I have dedicated the main site to the API. Therefore "/" is now the main docs home page. I also removed the other two creators since they have both faded off the planet of earth + they don't even work with me on the project. (The main Skin API page is officially back up for anyone wondering.)
=> Update Default Tydium Skin API Link + Minor Change

_data/providers.json
Include FREAKHOSTING as a hosting option in the providers list.
=> Add FREAKHOSTING as a provider

_data/providers.json
Bisect no longer requires contacting support for using Geyser. See https://www.bisecthosting.com/clients/index.php?rp=/knowledgebase/193/How-to-install-Geyser-and-Floodgate-on-a-Minecraft-Java-server.html. Have also confirmed this works by helping someone setup one in Discord.
=> Update with current instructions for Bisect Hosting

_docs/geyser/api.md
Use the latest link (https://repo.opencollab.dev/javadoc/maven-snapshots/org/geysermc/geyser/api/latest) for Javadocs so it's up to date.
=> Link to latest javadocs

_includes/setup/instructions/floodgate/standalone.md
Specifically, the loop that linked the same floodgate setup page is kind of confusing
=> Clarify Floodgate-Standalone setup guide

_docs/geyser/port-forwarding.md
The original documentation for Oracle Cloud/OCI didn't specify how to adjust the Virtual Cloud Network settings to allow Minecraft traffic to flow through. This PR adds steps on how to make this adjustment.
This PR also adds the steps required to configure the OS firewall for Oracle Linux (the default for Oracle Cloud).
=> Rewrite documentation for Oracle Cloud/OCI

_docs/geyser/geyser-command-line-arguments-and-system-properties.md
See https://github.com/GeyserMC/Geyser/pull/4554
=> Remove RakOfflinePacketLimit system property

_data/faq.yml, _docs/floodgate/faq.md
The URL only redirects to a broken `ww1` subdomain or malware websites.
=> docs: replace uuid.kejona.dev with mcprofile.io

_docs/geyser/port-forwarding.md
Title. 
If and when OVH resolves this, the advisory can and should be removed as the use of the `minecraftPocketEdition` is advisable over the more permissive `Other` filter.
Related/relevant:
https://github.com/ovh/infrastructure-roadmap/issues/186
https://github.com/GeyserMC/Geyser/pull/4554
=> Add advisory regarding OVH Game DDoS incompatibility
