GeyserMC/GeyserWiki

_data/providers.json
_docs/geyser/supported-hosting-providers.md

Move providers to a JSON file

---

_docs/floodgate/forms.md
_docs/floodgate/root.md
_docs/floodgate/setup.md
pages/index.md

*added more updated tutorial video.
*rerouting github wiki links to new wiki urls.
*removed all floodgate 1 references

rerouting github wiki links to new wiki urls.

---

_data/providers.json

Adds Cubes Hosting as a hosting provider to the wiki.

Add Cubes Hosting as a hosting provider.

---

_docs/other/geyser-fabric.md

Fix download link

---

_docs/geyser/faq.md

DBA added official support to Floodgate/GeyserMC

Update FAQ (DBA)

---

_data/providers.json

Remove HostMC4Free from providers list

---

Gemfile
Gemfile.lock
_data/toc.yml
_docs/floodgate/features.md
_docs/floodgate/linking.md

* Moved linking stuff into the Linking page 
* Added webrick into gem file to fix not being able to run site locally

Linking page fix & local serve fix

---

.github/CODEOWNERS

This is where all the provider and toc is.

Allow mods/triage to edit _data/

---

_data/providers.json

Suggested by Drakon and YHDiamond in the Geyser Discord.

Add OCI suffix to Oracle Cloud entry

---

_docs/floodgate/issues.md

`paper.yml` -> `paper-global.yml` in the `config` folder

Update paper config name

---

_docs/geyser/faq.md

Clarification or grammar suggestions are welcome. The entry is a bit longer than most of the others, so I could see wanting to shrink it.

Add Standalone vs Plugin entry

---

_data/providers.json

Taking out some dead host providers.

Update host providers

---

_data/toc.yml
_docs/geyser/custom-items.md

The link I use line 121 of the doc file won't work until custom items are merged into master.

Added custom item documentation

---

_docs/geyser/using-geyser-with-consoles.md

**Transparency note: This is my own app.**
The app is free and doesn't contain any ads unlike the other working ones listed currently.

Add Tempest as an alternative Android app for connecting

---

_docs/other/community-geyser-projects.md

Add new Skin API

---

_docs/other/community-geyser-projects.md

This won’t happen again in the future

Domain Update

---

_docs/floodgate/forms.md

lets not include recursive links

---

_docs/floodgate/features.md

fixes https://github.com/GeyserMC/GeyserWiki/issues/99

fix #99 - proper command permission node

---

_docs/floodgate/linking.md

lets make the link clickable

---

_docs/floodgate/setup.md

Adds to my tags pr https://github.com/GeyserMC/GeyserDiscordBot/pull/262 - but essentially, i've:
- updated the floodgate uuid converter to the new one that works
- changed floodgate-bukkit mentions to the spigot one
- added floodgate-fabric
- added info to floodgate on velocity - they have multiple options for player info forwarding

updated the floodgate setup page

---

_data/providers.json

see https://discord.com/channels/613163671870242838/613168464634576897/1069038712605917195

update mc-host24.de instructions

---

_data/providers.json

minehut now allows you to direct connect to servers via bedrock

Update Minehut description in providers

---

_data/providers.json

Updated falixnodes on providers list

---

_docs/geyser/setup.md
_docs/geyser/standalone.md

https://ci.opencollab.dev/job/Geyser/job/master/ as a download link doesnt work

fix download links

---

_docs/geyser/faq.md

- updated links
- 1.13.2 instead of 1.12.2
- let's not forget fabric
c

updated links, version and let's not forget about fabric

---

_docs/other/community-geyser-projects.md

Update name of GeyserHacks to Hurricane.

Update name of GeyserHacks to Hurricane.

---

_docs/floodgate/root.md

let us not forget floodgate-fabric on the main floodgate page

let us not forget floodgate-fabric

---

_docs/floodgate/linking.md

Update the URL for the default configuration file.

Update linking.md - URL

---

_docs/geyser/playit-gg.md

adapt to new playit.gg site! tbh, much easier to use. Also some cool options to ratelimit individual connections..

update playit.gg guide

---

_data/providers.json

Looks like mc-host24.de needs you to set your Bedrock address to your server ip.

[Needs conformation] mc-host24.de

---

_docs/geyser/anticheat-compatibility.md

Updated Spartan AntiCheat categorisation

Updated Spartan AntiCheat compatibility

---

_data/providers.json

Update the details regarding the use of Geyser at HeavyNode (hosting provider).

Update Geyser support details for HeavyNode

---

_docs/geyser/api.md

The path to writing the Geyser extension on this page is wrong.

Fix a path error.

---

_docs/geyser/custom-items.md

Fix an url error.

---

_docs/geyser/global-api.md

Fix erros.

---

_data/providers.json

fix some grammar issues in the providers.json file

fix some grammar issues

---

_docs/floodgate/features.md
_docs/floodgate/issues.md
_docs/floodgate/linking.md
_docs/floodgate/root.md

Fix hyperlinks.

---

_docs/geyser/forms.md

Update a link in forms.md

---

_docs/geyser/commands.md

Add a geyser tooltips command

---

_data/providers.json

Update informations about using Geyser on Hosterfy (hosting provider).

Add Hosterfy hosting provider instructions

---

_docs/geyser/extensions.md

Shouldn't link to an error example file.

Update a link.

---

_data/providers.json

Update providers.json Provider GPORTAL

---

_data/providers.json

Update providers.json - Added Kinetic Hosting

---

_data/providers.json

this is a description, not a template

fix providers list formatting

---

_docs/other/community-geyser-projects.md

Had updated my website recently and had forgotten to update the link here.

Update TC API link

---

_docs/geyser/custom-blocks.md
_docs/geyser/custom-items.md
_docs/geyser/custom-skulls.md

Merge together with https://github.com/GeyserMC/Geyser/pull/4041

Add tags to custom items, fix code examples

---

_data/faq.yml

Update java version to keep up with Geyser-Spigot jar.

Update faq.yml - What server versions does Geyser support?

---

_data/providers.json

See https://shockbyte.com/billing/knowledgebase/173/Introduction-to-GeyserMCorDragonProxy-How-GeyserMC-Works.html for reference

Update shockbyte instructions

---

_data/faq.yml
_docs/geyser/common-issues.md
_docs/geyser/creating-a-startup-script.md
_includes/setup/instructions/geyser/selfhost/standalone.md

Geyser now needs java 17 to run

Update java ver

---

_data/providers.json

Added VoltHosting to the providers list upon request from a client.

Added VoltHosting to the providers list

---

_data/providers.json

Added VexyHost to the providers list

Added VexyHost to the providers list

---

_data/faq.yml
_includes/setup/instructions/geyser/provider/spigot.md
_includes/setup/instructions/geyser/selfhost/spigot.md

Update ViaVersion/ViaBackwards links to hangar

Update ViaVersion/ViaBackwards links

---

_docs/geyser/custom-items.md

Documents https://github.com/GeyserMC/Geyser/pull/4484

Document custom items creative category/group setting

---

_docs/geyser/geyser-command-line-arguments-and-system-properties.md
_docs/geyser/understanding-the-config.md

See https://github.com/GeyserMC/Geyser/pull/4532.

Document new network configuration

---

_docs/geyser/geyser-command-line-arguments-and-system-properties.md

See https://github.com/GeyserMC/Geyser/pull/4598

Add system property Geyser.RakSendCookie to allow disabling cookie send

---

_docs/other/community-geyser-projects.md

I would appreciate if this plugin of mine was added, as I have put alot of time into it and would love to develop it further and have more servers using it :)

Add GeyserExtras to Community Projects page

---

_data/providers.json

Add [Lilypad](https://lilypad.gg) to Supported Hosting Providers list

Add Lilypad to providers.json

---

_data/providers.json

Add MCFORFREE to the providers list

---

_data/providers.json

I added arth hosting and re-ordered apex hosting and aternos to be in alphabetical order

Add Arth Hosting and reorganize

---

_docs/geyser/current-limitations.md

I've also attached the relevant Github issues to e.g. show relevant context/potential workarounds

Update current limitations page

---

_docs/geyser/api.md
_docs/geyser/current-limitations.md
_docs/geyser/extensions.md
_docs/geyser/global-api.md
_docs/other/geyseroptionalpack.md
_docs/other/hurricane.md

- Add the `skin` package instructions in geyser/api.md
- Update description and link for onebeastchris/Hurricane
- Change some plain text to hyperlinks
- Replace some of the quotes in a block of code in extensions.md(In this document, quotation marks are used to include files, commands, and some words, it is very unintuitive and different from the style of other documents)

Update some outdate contents,add skin package instructions and so on
